### PR TITLE
Upgrade to new packages interface

### LINKED ISSUE #4: build failed
## build failed

src/github.com/stamblerre/gocode/internal/suggest/suggest.go:138:3: cannot use func literal (type func(*token.FileSet, string) (*ast.File, error)) as type func(*token.FileSet, string, []byte) (*ast.File, error) in field value

[packages.Config.ParseFile](https://github.com/golang/tools/blob/master/go/packages/packages.go#L108)

### PR DESCRIPTION
**Pull request by egonelbre**
Fixes #4

### CODE REVIEW

**Comment by yfwz100** [comment]
Seems to work fine.

**Comment by zeybek** [comment]
Hope it will be merged soon !

**Comment by joaojeronimo** [comment]
This is creating a new variable `srcdata` that is not used, while `src` is still being initialised as an empty interface right on the next line. Would [this](https://github.com/stamblerre/gocode/pull/6/files#diff-2f3534b5589688ddc04474bf8087dfe5R138) be better ?

**Comment by egonelbre** [comment]
@joaojeronimo changing it such will change the behavior of the code. It might be still correct, but I don't know the code that well to say for certain.

**Comment by Scapal** [comment]
Please merge, [Microsoft/vscode-go](/Microsoft/vscode-go) is unusable and it is probably the largest usage of this library. 

No change is breaking most projects depending on your lib.

**Comment by stamblerre** [comment]
Sorry about not merging this earlier--somehow didn't get a notification for this. Should be fixed now.

**Pull request closed without merging**
